services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:supersecretpassword@db/trially
      - SECRET_KEY=goQmOtw6feiepsLSUBItjSqGcqmUNoQn34j0599j6to
    command: fastapi dev main.py --host 0.0.0.0
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=trially
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - trially-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  trially-data: